{{- if .Values.persistence.enabled }}
{{- if not .Values.persistence.existingClaim -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.name }}-storage-claim
  annotations:
    "helm.sh/resource-policy": "keep"
spec:
  storageClassName: {{ .Values.persistence.storage.class }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.storage.uploads.size }}
{{- end }}
{{- end }}