{{ if .Values.postgresql.auth.create }}
{{ $databaseSecret := randAlphaNum 32 | b64enc | quote }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.auth.existingSecret }}
data:
  postgres-password: {{ $databaseSecret }}
  password: {{ $databaseSecret }}
type: Opaque
{{ end }}