apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-http
  labels:
    app: {{ .Values.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: {{ .Values.name }}-http
{{ if eq .Values.service.type "NodePort" }}
    port: 8080
    nodePort: {{ .Values.service.port.http }}
    targetPort: 8080
{{ else }}
    port: 8080
    targetPort: http
{{ end }}
    protocol: TCP
  selector:
    app: {{ .Values.name }}
{{ if not .Values.ingress.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-https
  labels:
    app: {{ .Values.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: https
{{ if eq .Values.service.type "NodePort" }}
    port: 8443
    nodePort: {{ .Values.service.port.https }}
    targetPort: 8443
{{ else }}
    port: 8443
    targetPort: {{ .Values.service.port.https }}
{{ end }}
    protocol: TCP
  selector:
    app: {{ .Values.name }}
{{ end }}